[application]
name = "web"
default_platform = "web"
asset_dir = "assets"

[web.app]
title = "App Template DX"

[web.watcher]
watch_path = ["src", "../../shared"]
reload_html = true
index_on_404 = true
