[package]
name = "shared-models"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
criterion = { workspace = true }
serde_json = "1.0"

[[bench]]
name = "user_benchmark"
harness = false
